// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pslvrmwpntqzuyzmdazo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzbHZybXdwbnRxenV5em1kYXpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNDgyNTQsImV4cCI6MjA2NzcyNDI1NH0.p6zWGf7MO2Nov-d0wWO1DfjmJj5trAGBiEuE7OcGx3I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});